### ISSUE TITLE
Lack of write permission even in root user

### ISSUE THREAD

**Issue by rizary** [cachix/ghcide-nix#15]
I am using NixOS in my Windows' hyper-v. 

Installing cachix works fine. But when I execute `cachix use hercules-ci`, I got the following error:
```
MustBeRoot "Run command as root Or execute: $ echo \"trusted-users = root $USER\" | sudo tee -a /etc/nix/nix.conf && sudo pkill nix-daemon"
```

Then I use `sudo` and got the `due to lack of write permissions`. So I use `cachix use hercules-ci --nixos-folder /etc/mynixos/` and I keep getting error `Could not install NixOS configuration to /etc/nixos/ due to lack of write permissions`.

**Comment by domenkozar** [comment]
@Rizary what's your `cachix --version`?

**Comment by rizary** [comment]
@domenkozar 

```
cachix --version
cachix 0.3.0
```

**Comment by domenkozar** [comment]
That version has a bug, hopefully cachix will hit nixpkgs tomorrow and you can upgrade.

You can install development version meanwhile:

```
nix-env -if https://github.com/cachix/cachix/tarball/master --substituters https://cachix.cachix.org --trusted-public-keys cachix.cachix.org-1:eWNHQldwUO7G2VkjpnjDbWwy4KQ/HNxht7H4SSoMckM=
```

**Comment by rizary** [comment]
@domenkozar it works, thank you.
