### ISSUE TITLE
Prevent re-downloading ghc865

### ISSUE THREAD

**Issue by v217** [cachix/ghcide-nix#16]
I am new to nix. So sorry if there is a trivial answer.  
I installed ghcide, everything works great, however cachix/nix redownloads and installs ghc865.  
If possible it would be great if cachix/nix would use the existing nix ghc865 installation.  
Right now I have two nix ghc865 installs. Thanks for the best Haskell IDE!

**Comment by v217** [comment]
`nix-store --optimise` is may be a work around. Not sure whether there are downsides?

**Comment by domenkozar** [comment]
No downsides besides that you need to run it. That's really the only choice you have.
