### ISSUE TITLE
Update to ghcide 0.0.4 

### ISSUE THREAD

**Issue by PierreR** [cachix/ghcide-nix#21]
Is is ok to PR a change to sources.json or do you prefer an issue ? 

There is no rush on my side but some fixes from 0.0.4 look interesting.

**Comment by PierreR** [comment]
Actually looking at Update to 8bdc1ff5874fe25179748404a52c5496493089c7 I am not sure how or if I w(s)ould update haskell.nix ... So it is probably safer if I don't PR ;-)

**Comment by roberth** [comment]
We were using an update script to generate those files. https://github.com/hercules-ci/ghcide-nix/pull/20 fixes that and updates ghcide to 0.0.4. I hope we can merge that soon.

**Comment by domenkozar** [comment]
done in https://github.com/hercules-ci/ghcide-nix/pull/20
