### ISSUE TITLE
Invalid signature on Darwin

### ISSUE THREAD

**Issue by backuitist** [cachix/ghcide-nix#25]
I've just setup cachix following the instructions but failed to validate the store path signatures:
```
warning: substituter 'https://hercules-ci.cachix.org' does not have a valid signature for path '/nix/store/0wlvvhyy3cg1nrl2blzsvccm4bhf8m3d-x509-system-exactdep'
```

Here is my nix conf:
```
bash-3.2$ cat ~/.config/nix/nix.conf
substituters = https://cache.nixos.org https://hercules-ci.cachix.org
trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hercules-ci.cachix.org-1:ZZeDl9Va+xe9j+KqdzoBZMFJHVQ42Uu/c/1/KMC5Lw0=
```

**Comment by domenkozar** [comment]
It works for me locally. 

Are you running it under the same user?
What user is the owner of your /nix/store folder?

**Comment by backuitist** [comment]
I think I used `--option trusted-public-keys` with my own cache and forgot to add the cachix key...
Sorry!
