### ISSUE TITLE
GHC 8.8.1 support

### ISSUE THREAD

**Issue by domenkozar** [cachix/ghcide-nix#3]
Upstream: https://github.com/digital-asset/ghcide/issues/33

**Comment by expipiplus1** [comment]
Hi @domenkozar, the upstream dependency has been resolved now :)

**Comment by domenkozar** [comment]
See #17

**Comment by expipiplus1** [comment]
Thanks!

**Comment by domenkozar** [comment]
Blocked on https://github.com/haskell/hackage-server/issues/852

**Comment by sloane-shark** [comment]
Is there any workaround or hack I can use to get ghcide working with ghc883 under nix?

**Comment by domenkozar** [comment]
You can use #32 branch with linux cache, working on getting macos there as well.

**Comment by srid** [comment]
> Blocked on haskell/hackage-server#852

Looks like this was resolved as well!

**Comment by domenkozar** [comment]
Fixed in https://github.com/cachix/ghcide-nix/pull/32

**Comment by expipiplus1** [comment]
Thanks!
