### ISSUE TITLE
ghcide needs package ghc for runtime version checking

### ISSUE THREAD

**Issue by jkopanski** [cachix/ghcide-nix#45]
I've just started new project (built using haskell.nix infrastructure). Since it is new it has very few dependencies. To my surprise ghcide refused to work with message:

```sh
Message:
  ghcide compiled against GHC 8.8.3 but currently using an unknown version of GHC . This is
  unsupported, ghcide must be compiled with the same GHC version as the project.
  CallStack (from HasCallStack):
  error, called at src/Development/IDE/GHC/Util.hs:177:17 in
  ghcide-0.1.0-BVBdAIZmBIjJ0E7pJvTGCd:Development.IDE.GHC.Util
```

It was weird since the same ghc/ghcide combo derivation worked for a larger project.

It turns out that ghcide uses `runTimeVersion` from `ghc-check` to get version, which in turn uses [getGhcVersion](http://hackage.haskell.org/package/ghc-check-0.1.0.3/docs/src/GHC.Check.Internal.html#getGhcVersion), which needs `ghc` package.
It so happened that `ghc` was pulled in the bigger project by some other dependency.

Right now I just added `ghc` to cabal file to get ghcide working, put perhaps some nix magic should pull it in automatically?

**Comment by mpickering** [comment]
I think this is really a problem with ghcide. See https://github.com/digital-asset/ghcide/issues/534

**Comment by domenkozar** [comment]
@jkopanski could you try latest `ghc-8.8` branch? I think making `ghc` reinstallable wasn't really needed.

**Comment by jkopanski** [comment]
@domenkozar I've tried it today but I run into #46 and I am having:
```
ghcide compiled against GHC 8.8.2 but currently using an unknown version of GHC . This is
  unsupported, ghcide must be compiled with the same GHC version as the project.
```

anyway as @mpickering pointed out this is probably upstream issue, not sure if it's reasonable to ask for workarounds here.

**Comment by domenkozar** [comment]
I'll block #32 on https://github.com/digital-asset/ghcide/pull/535
